### PR TITLE
Add a simple web-based remote control UI

### LINKED ISSUE #10: Provide a web-based remote control
Provide a web-based remote control to allow slide selection on a remote device (phone, tablet, watch ...)

### PR DESCRIPTION
**Pull request by duncan-bayne**
Adds a very simple web-based remote control UI for org-present.  The intent is to allow the user to remotely control a presentation from a mobile device like a phone.

There is definitely scope for improvement; amongst the things this PR _doesn't_ provide are:
- authentication / authorization
- multiple presentations
- auto-disconnection timeouts

remote-screenshot_nexus4_angle1

(fixes #10)

### CODE REVIEW

**Comment by jaseemabid** [comment]
Interesting concept indeed. I'm worried primarily about 1) code growth, 2) security implications of listening to a TCP socket from emacs.

**Comment by rlister** [comment]
Super interesting. Busy at a conference right now but I'll take a good look at this in a couple of days. Thanks.

**Comment by duncan-bayne** [comment]
Thanks :smile: I should mention that this is my first 'serious' Emacs Lisp work, so it probably needs closer review than you'd expect.

**Comment by duncan-bayne** [comment]
@rlister anything I can do to help expedite merging this?  Hoping to use it for presentations soon w/o running a forked org-present locally :smile:

**Comment by rlister** [comment]
@duncan-bayne Hi Duncan, really sorry I've not been responsive. Been super busy with work and travel. I really, really like this idea still, but I think I don't want a tcp socket into base `org-present`. I'm keen to keep it small and minimal, and build extras as plugins, or packages that sit on top of `org-present`.

To this end we could perhaps add hooks to e.g. `org-present-{next,prev}` and then add a package or file for `org-present-remote`. I will hopefully have a little time to work on this in the new year (product launch Jan 5th, so perhaps after that).

What do you think?
Thanks.

**Comment by duncan-bayne** [comment]
@rlister No problem at all; I've been flat out the past few months and only now have an opportunity to look at this again.

Yes, I think that would work nicely.  If you can add the hooks and push a new version, I'll create an entirely new package that makes use of the hooks.

**Comment by duncan-bayne** [comment]
Hi @rlister, any news on availability of hooks?  Happy to work on this ASAP.

**Comment by rlister** [comment]
@duncan-bayne Sorry, my anticipated hiatus in release schedule never arrived, and, if anything, has intensified recently. I still intend to work on this, but can't justify the time right now. I will prioritize this work should my time become slightly more fungible.

**Comment by duncan-bayne** [comment]
I know what that's like :-(

Perhaps I could do the work? That is, close this PR, and open a new one with the changes necessary to expose the hooks I need?

**Comment by rlister** [comment]
@duncan-bayne A PR adding the hooks would be most gratefully received :-)

**Comment by duncan-bayne** [comment]
_Finally_ got to this!  See https://github.com/rlister/org-present/pull/13.

**Comment by duncan-bayne** [comment]
I think we can close this PR :)  I've created a package called `org-present-remote`, and opened a PR to add it to MELPA (https://github.com/melpa/melpa/pull/5658).

**Comment by duncan-bayne** [comment]
FYI @rlister org-present-remote is now merged into MELPA and installable :tada:

**Pull request closed without merging**
